site_name: NR Control

theme:
    name: material
    palette:
      primary: black
      accent: deep purple
      

nav:
  - Home: index.md
  - Visão do produto e projeto:
    - Visão de produto: product.md  
    - Visão de projeto: project.md
    - Processos de desenvolvimento de software: process.md
  - Requisitos do produto: 
    - Definições: definitions.md
    - Critérios de aceitação: acceptance.md
    - Backlog: backlog.md
  - Arquitetura: architecture.md
  - Sprints: sprints.md
  - Workflow: workflow.md
  - Padrões de interface: uipattern.md
  - Lições aprendidas: lessons.md
